# database.py
from typing import List
from app.schemas import BookOut

BOOKS: List[BookOut] = [
    BookOut(
        id=1,
        title="The Great Gatsby",
        author="F. Scott Fitzgerald",
        isbn="9780743273565",
        category="Fiction",
        copies=5,
    ),
    BookOut(
        id=2,
        title="To Kill a Mockingbird",
        author="Harper Lee",
        isbn="9780061120084",
        category="Fiction",
        copies=3,
    ),
    BookOut(
        id=3,
        title="1984",
        author="George Orwell",
        isbn="9780451524935",
        category="Dystopian",
        copies=4,
    ),
    BookOut(
        id=4,
        title="Pride and Prejudice",
        author="Jane Austen",
        isbn="9780141439518",
        category="Romance",
        copies=2,
    ),
    BookOut(
        id=5,
        title="The Catcher in the Rye",
        author="J.D. Salinger",
        isbn="9780316769488",
        category="Fiction",
        copies=6,
    ),
    BookOut(
        id=6,
        title="The Hobbit",
        author="J.R.R. Tolkien",
        isbn="9780547928227",
        category="Fantasy",
        copies=8,
    ),
    BookOut(
        id=7,
        title="Fahrenheit 451",
        author="Ray Bradbury",
        isbn="9781451673319",
        category="Dystopian",
        copies=4,
    ),
    BookOut(
        id=8,
        title="The Alchemist",
        author="Paulo Coelho",
        isbn="9780062315007",
        category="Adventure",
        copies=7,
    ),
    BookOut(
        id=9,
        title="Brave New World",
        author="Aldous Huxley",
        isbn="9780060850524",
        category="Dystopian",
        copies=5,
    ),
    BookOut(
        id=10,
        title="The Picture of Dorian Gray",
        author="Oscar Wilde",
        isbn="9780141439570",
        category="Fiction",
        copies=3,
    ),
    BookOut(
        id=11,
        title="The Lord of the Rings",
        author="J.R.R. Tolkien",
        isbn="9780544003415",
        category="Fantasy",
        copies=10,
    ),
    BookOut(
        id=12,
        title="The Chronicles of Narnia",
        author="C.S. Lewis",
        isbn="9780066238500",
        category="Fantasy",
        copies=9,
    ),
    BookOut(
        id=13,
        title="The Kite Runner",
        author="Khaled Hosseini",
        isbn="9781594631931",
        category="Fiction",
        copies=4,
    ),
    BookOut(
        id=14,
        title="The Da Vinci Code",
        author="Dan Brown",
        isbn="9780307474278",
        category="Mystery",
        copies=6,
    ),
    BookOut(
        id=15,
        title="The Hunger Games",
        author="Suzanne Collins",
        isbn="9780439023528",
        category="Dystopian",
        copies=5,
    ),
    BookOut(
        id=16,
        title="The Fault in Our Stars",
        author="John Green",
        isbn="9780525478812",
        category="Romance",
        copies=3,
    ),
    BookOut(
        id=17,
        title="The Book Thief",
        author="Markus Zusak",
        isbn="9780375842207",
        category="Historical Fiction",
        copies=4,
    ),
    BookOut(
        id=18,
        title="The Road",
        author="Cormac McCarthy",
        isbn="9780307387899",
        category="Dystopian",
        copies=2,
    ),
    BookOut(
        id=19,
        title="Life of Pi",
        author="Yann Martel",
        isbn="9780156027328",
        category="Adventure",
        copies=3,
    ),
    BookOut(
        id=20,
        title="The Hitchhiker's Guide to the Galaxy",
        author="Douglas Adams",
        isbn="9780345391803",
        category="Science Fiction",
        copies=5,
    ),
    BookOut(
        id=21,
        title="The Time Machine",
        author="H.G. Wells",
        isbn="9780451530707",
        category="Science Fiction",
        copies=4,
    ),
    BookOut(
        id=22,
        title="Dune",
        author="Frank Herbert",
        isbn="9780441013593",
        category="Science Fiction",
        copies=6,
    ),
    BookOut(
        id=23,
        title="Ender's Game",
        author="Orson Scott Card",
        isbn="9780765370624",
        category="Science Fiction",
        copies=3,
    ),
]


